const progress=document.getElementById('progress');
window.addEventListener('scroll',()=>{const h=document.documentElement;const max=h.scrollHeight-h.clientHeight;progress.style.width=(max?((h.scrollTop/max)*100):0)+'%';},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.06});
document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
const data={
 fraud:{meta:'FRAUD & RISK · CSPIMAGING 4.2.0.x',title:'Fraud & Risk Validation',body:`<p>Designed and delivered configurable Self-on-Self deposit fraud validation, owning HLD/LLD, account and routing comparison logic, configuration strategy, and ATM/Completion integration for operator correction and re-validation.</p><p>Strengthened deposit-risk decisioning by integrating the Risk Validation Adapter with production-grade TLS/mTLS, fixing item-update re-evaluation defects, and exposing standardized Red / Yellow / Green risk indicators through platform APIs.</p><p><strong>Result:</strong> risk decisions remain consistent when deposit details change, while downstream banking systems receive a standard risk signal they can act on.</p><div class="tags"><span>Java</span><span>Spring Boot</span><span>REST</span><span>TLS/mTLS</span><span>RVA</span></div>`},
 migration:{meta:'PLATFORM MODERNIZATION · 8 SERVICES',title:'JDK 8/11 → 17 Migration',body:`<p>Drove a JDK 8/11 to 17 migration across 8 services, including a legacy monolith with more than 3,000 build issues.</p><p>Resolved compatibility and resource-leak problems across the migration, restored builds, and completed the production rollout with zero downtime.</p><p><strong>Result:</strong> a supported modern runtime without disrupting existing banking deployments.</p><div class="tags"><span>Java 17</span><span>Maven</span><span>Compatibility</span><span>Zero Downtime</span></div>`},
 security:{meta:'APPSEC · PI 25.3 / PI 26.1',title:'Application Security Remediation',body:`<p>Remediated 100+ security vulnerabilities across multiple production services, including 40+ Critical and 60+ High-severity findings.</p><p>Worked across Mend, JFrog Xray, SonarQube, and Coverity to address vulnerable dependencies and code-level issues, porting fixes across 3 repositories and 5+ supported release lines.</p><p><strong>Result:</strong> cleared AppSec certification gates for PI 25.3 and PI 26.1 while maintaining several supported product versions.</p><div class="tags"><span>Mend</span><span>JFrog Xray</span><span>SonarQube</span><span>Coverity</span><span>CVE Remediation</span></div>`},
 ai:{meta:'AI · DEVELOPER EXPERIENCE',title:'AI-Powered Log Triage',body:`<p>Built custom Cursor Skills integrating OpenAI, Gemini, and Claude APIs to correlate application logs with recurring failure patterns and generate root-cause and remediation guidance.</p><p>The workflow reduced developer log-triage effort from roughly 45 minutes to 15 minutes — applying LLMs to a concrete engineering workflow rather than as a generic chatbot.</p><div class="tags"><span>OpenAI</span><span>Gemini</span><span>Claude</span><span>Cursor</span><span>RCA</span></div>`}
};
const modal=document.getElementById('modal'),content=document.getElementById('modal-content');
document.querySelectorAll('.work-card[data-modal]').forEach(c=>c.addEventListener('click',()=>{const d=data[c.dataset.modal];content.innerHTML=`<div class="modal-meta">${d.meta}</div><h2>${d.title}</h2>${d.body}`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelector('.modal-close').addEventListener('click',closeModal);document.querySelector('.modal-backdrop').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
